### ISSUE TITLE
Dart Study roadmap

### ISSUE THREAD

**Issue by kyungkoo** [kyungkoo/dart-101#1]
- [ ] [A Tour of the Dart Language](https://www.dartlang.org/guides/language/language-tour)
- [ ] [Effective Dart](https://www.dartlang.org/guides/language/effective-dart)
- [ ] [A Tour of the Dart Libraries](https://www.dartlang.org/guides/libraries/library-tour)
